# Generated by Django 4.0.3 on 2022-09-19 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_npud', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ao_acces',
            new_name='ao_access',
        ),
        migrations.AlterModelOptions(
            name='ao_access',
            options={'verbose_name': 'ao_access', 'verbose_name_plural': 'ao_access'},
        ),
    ]
