# Generated by Django 4.1.1 on 2022-10-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_pnud', '0002_indicadores_empleo_indicadores_ingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mar_harvest_tonnes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.FloatField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Mar_harvest_tonnes',
                'verbose_name_plural': 'Mar_harvest_tonnes',
            },
        ),
    ]
