# Generated by Django 4.1.1 on 2022-10-12 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_pnud', '0003_mar_harvest_tonnes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mar_harvest_tonnes',
            old_name='tipo',
            new_name='zona',
        ),
    ]
