from django.contrib import admin
from db_pnud.models import *
admin.site.register(ao_access)
admin.site.register(ao_need)
admin.site.register(base_metas_estado_tendencia)
admin.site.register(base_puntos_referencia)
admin.site.register(cw_chemical_trend)
admin.site.register(cw_nutrient_trend)
admin.site.register(cw_pathogen_trend)
admin.site.register(cw_trash_trend)
admin.site.register(eco_status)
admin.site.register(eco_trend)
admin.site.register(fis_b_bmsy)
admin.site.register(fis_meancatch)
admin.site.register(hab_mangrove_extent)
admin.site.register(hab_mangrove_health)
admin.site.register(hab_mangrove_trend)
admin.site.register(hab_saltmarsh_extent)
admin.site.register(hab_saltmarsh_health)
admin.site.register(hab_saltmarsh_trend)
admin.site.register(le_sector_weight)
admin.site.register(liv_status)
admin.site.register(liv_trend)
admin.site.register(spp_status)
admin.site.register(spp_trend)
admin.site.register(tr_sustainability)
admin.site.register(tr_visit_sq_pct_tourism)
